#ifndef _SED_IDL_
#define _SED_IDL_

interface SeD {

  /** Let check if this server is alive. */
  long ping();

  /** Send an order for the SeD to connect to a new parent */
  long bindParent(in string parentName);
  /** Send an order for the SeD to disconnect from its parent */
  long disconnect();
  /** Send an order for the SeD to kill itself */
  long removeElement();


};


#endif // _SED_IDL_
