#ifndef _AGENT_IDL_
#define _AGENT_IDL_



/****************************************************************************/
/* Agent interface                                                          */
/****************************************************************************/

interface Agent {

  /** Used to test if this agent is alive. */
  long ping();
};


#endif // _AGENT_IDL_

