/****************************************************************************/
/* DIET local agent IDL description                                         */
/*                                                                          */
/*  Author(s):                                                              */
/*    - Sylvain DAHAN (Sylvain.Dahan@lifc.univ-fcomte.fr)                   */
/*                                                                          */
/* $LICENSE$                                                                */
/****************************************************************************/
/* $Id$
 * $Log$
 * Revision 1.1  2007/01/24 13:09:39  aamar
 * DIET idl files added.
 *
 * Revision 1.1.1.1  2006/12/08 18:11:12  aamar
 * Import DIET DashBoard without svn files and unnecessary files.
 *
 * Revision 1.1  2003/04/10 12:31:47  pcombes
 * Replace localAgent.idl. Update doxygen doc.
 *
 ****************************************************************************/

#ifndef _LOCAL_AGENT_IDL_
#define _LOCAL_AGENT_IDL_

#include "Agent.idl"


interface LocalAgent : Agent {

  /**
   * Message posting function:<br>
   * This call is asynchronous. The request message REQ is kept
   * in an internal list and processed as soon as possible.
   */
  oneway void getRequest(in corba_request_t req);

};

#endif // _LOCAL_AGENT_IDL_
