/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sysfera.vishnu.api.ims.internal;

public class EObject {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected EObject(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EObject obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        VISHNU_IMSJNI.delete_EObject(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public EObject() {
    this(VISHNU_IMSJNI.new_EObject(), true);
  }

  public void _initialize() {
    VISHNU_IMSJNI.EObject__initialize(swigCPtr, this);
  }

  public SWIGTYPE_p_ecore__EClass eClass() {
    long cPtr = VISHNU_IMSJNI.EObject_eClass(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ecore__EClass(cPtr, false);
  }

  public boolean eIsProxy() {
    return VISHNU_IMSJNI.EObject_eIsProxy(swigCPtr, this);
  }

  public int eResource() {
    return VISHNU_IMSJNI.EObject_eResource(swigCPtr, this);
  }

  public EObject eContainer() {
    long cPtr = VISHNU_IMSJNI.EObject_eContainer(swigCPtr, this);
    return (cPtr == 0) ? null : new EObject(cPtr, false);
  }

  public SWIGTYPE_p_ecore__EStructuralFeature eContainingFeature() {
    long cPtr = VISHNU_IMSJNI.EObject_eContainingFeature(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ecore__EStructuralFeature(cPtr, false);
  }

  public SWIGTYPE_p_ecore__EReference eContainmentFeature() {
    long cPtr = VISHNU_IMSJNI.EObject_eContainmentFeature(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ecore__EReference(cPtr, false);
  }

  public SWIGTYPE_p_std__listT_ecore__EObject_p_t eContents() {
    return new SWIGTYPE_p_std__listT_ecore__EObject_p_t(VISHNU_IMSJNI.EObject_eContents(swigCPtr, this), true);
  }

  public int eAllContents() {
    return VISHNU_IMSJNI.EObject_eAllContents(swigCPtr, this);
  }

  public SWIGTYPE_p_std__listT_ecore__EObject_p_t eCrossReferences() {
    return new SWIGTYPE_p_std__listT_ecore__EObject_p_t(VISHNU_IMSJNI.EObject_eCrossReferences(swigCPtr, this), true);
  }

  public SWIGTYPE_p_ecorecpp__mapping__any eGet(SWIGTYPE_p_ecore__EStructuralFeature _feature) {
    return new SWIGTYPE_p_ecorecpp__mapping__any(VISHNU_IMSJNI.EObject_eGet__SWIG_0(swigCPtr, this, SWIGTYPE_p_ecore__EStructuralFeature.getCPtr(_feature)), true);
  }

  public SWIGTYPE_p_ecorecpp__mapping__any eGet(SWIGTYPE_p_ecore__EStructuralFeature _feature, boolean _resolve) {
    return new SWIGTYPE_p_ecorecpp__mapping__any(VISHNU_IMSJNI.EObject_eGet__SWIG_1(swigCPtr, this, SWIGTYPE_p_ecore__EStructuralFeature.getCPtr(_feature), _resolve), true);
  }

  public void eSet(SWIGTYPE_p_ecore__EStructuralFeature _feature, SWIGTYPE_p_ecorecpp__mapping__any _newValue) {
    VISHNU_IMSJNI.EObject_eSet__SWIG_0(swigCPtr, this, SWIGTYPE_p_ecore__EStructuralFeature.getCPtr(_feature), SWIGTYPE_p_ecorecpp__mapping__any.getCPtr(_newValue));
  }

  public boolean eIsSet(SWIGTYPE_p_ecore__EStructuralFeature _feature) {
    return VISHNU_IMSJNI.EObject_eIsSet__SWIG_0(swigCPtr, this, SWIGTYPE_p_ecore__EStructuralFeature.getCPtr(_feature));
  }

  public void eUnset(SWIGTYPE_p_ecore__EStructuralFeature _feature) {
    VISHNU_IMSJNI.EObject_eUnset__SWIG_0(swigCPtr, this, SWIGTYPE_p_ecore__EStructuralFeature.getCPtr(_feature));
  }

  public SWIGTYPE_p_ecorecpp__mapping__any eInvoke(SWIGTYPE_p_ecore__EOperation _operation, SWIGTYPE_p_std__listT___ecorecpp__mapping__any_t _arguments) {
    return new SWIGTYPE_p_ecorecpp__mapping__any(VISHNU_IMSJNI.EObject_eInvoke(swigCPtr, this, SWIGTYPE_p_ecore__EOperation.getCPtr(_operation), SWIGTYPE_p_std__listT___ecorecpp__mapping__any_t.getCPtr(_arguments)), true);
  }

  public SWIGTYPE_p_ecorecpp__mapping__any eGet(int _featureID, boolean _resolve) {
    return new SWIGTYPE_p_ecorecpp__mapping__any(VISHNU_IMSJNI.EObject_eGet__SWIG_2(swigCPtr, this, _featureID, _resolve), true);
  }

  public void eSet(int _featureID, SWIGTYPE_p_ecorecpp__mapping__any _newValue) {
    VISHNU_IMSJNI.EObject_eSet__SWIG_1(swigCPtr, this, _featureID, SWIGTYPE_p_ecorecpp__mapping__any.getCPtr(_newValue));
  }

  public boolean eIsSet(int _featureID) {
    return VISHNU_IMSJNI.EObject_eIsSet__SWIG_1(swigCPtr, this, _featureID);
  }

  public void eUnset(int _featureID) {
    VISHNU_IMSJNI.EObject_eUnset__SWIG_1(swigCPtr, this, _featureID);
  }

  public SWIGTYPE_p_ecore__EClass _eClass() {
    long cPtr = VISHNU_IMSJNI.EObject__eClass(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ecore__EClass(cPtr, false);
  }

  public void _setEContainer(EObject _eContainer, SWIGTYPE_p_ecore__EStructuralFeature _eContainingFeature) {
    VISHNU_IMSJNI.EObject__setEContainer(swigCPtr, this, EObject.getCPtr(_eContainer), _eContainer, SWIGTYPE_p_ecore__EStructuralFeature.getCPtr(_eContainingFeature));
  }

}
