/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sysfera.vishnu.api.ims.internal;

public class MetricHistOp extends EObject {
  private long swigCPtr;

  protected MetricHistOp(long cPtr, boolean cMemoryOwn) {
    super(VISHNU_IMSJNI.SWIGMetricHistOpUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MetricHistOp obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        VISHNU_IMSJNI.delete_MetricHistOp(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public MetricHistOp() {
    this(VISHNU_IMSJNI.new_MetricHistOp(), true);
  }

  public void _initialize() {
    VISHNU_IMSJNI.MetricHistOp__initialize(swigCPtr, this);
  }

  public long getStartTime() {
    return VISHNU_IMSJNI.MetricHistOp_getStartTime(swigCPtr, this);
  }

  public void setStartTime(long _startTime) {
    VISHNU_IMSJNI.MetricHistOp_setStartTime(swigCPtr, this, _startTime);
  }

  public long getEndTime() {
    return VISHNU_IMSJNI.MetricHistOp_getEndTime(swigCPtr, this);
  }

  public void setEndTime(long _endTime) {
    VISHNU_IMSJNI.MetricHistOp_setEndTime(swigCPtr, this, _endTime);
  }

  public SWIGTYPE_p_ecorecpp__mapping__any eGet(int _featureID, boolean _resolve) {
    return new SWIGTYPE_p_ecorecpp__mapping__any(VISHNU_IMSJNI.MetricHistOp_eGet(swigCPtr, this, _featureID, _resolve), true);
  }

  public void eSet(int _featureID, SWIGTYPE_p_ecorecpp__mapping__any _newValue) {
    VISHNU_IMSJNI.MetricHistOp_eSet(swigCPtr, this, _featureID, SWIGTYPE_p_ecorecpp__mapping__any.getCPtr(_newValue));
  }

  public boolean eIsSet(int _featureID) {
    return VISHNU_IMSJNI.MetricHistOp_eIsSet(swigCPtr, this, _featureID);
  }

  public void eUnset(int _featureID) {
    VISHNU_IMSJNI.MetricHistOp_eUnset(swigCPtr, this, _featureID);
  }

  public SWIGTYPE_p_ecore__EClass _eClass() {
    long cPtr = VISHNU_IMSJNI.MetricHistOp__eClass(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ecore__EClass(cPtr, false);
  }

}
