/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sysfera.vishnu.api.ims.internal;

public class Metric extends EObject {
  private long swigCPtr;

  protected Metric(long cPtr, boolean cMemoryOwn) {
    super(VISHNU_IMSJNI.SWIGMetricUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Metric obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        VISHNU_IMSJNI.delete_Metric(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Metric() {
    this(VISHNU_IMSJNI.new_Metric(), true);
  }

  public void _initialize() {
    VISHNU_IMSJNI.Metric__initialize(swigCPtr, this);
  }

  public int getType() {
    return VISHNU_IMSJNI.Metric_getType(swigCPtr, this);
  }

  public void setType(int _type) {
    VISHNU_IMSJNI.Metric_setType(swigCPtr, this, _type);
  }

  public double getValue() {
    return VISHNU_IMSJNI.Metric_getValue(swigCPtr, this);
  }

  public void setValue(double _value) {
    VISHNU_IMSJNI.Metric_setValue(swigCPtr, this, _value);
  }

  public int getTime() {
    return VISHNU_IMSJNI.Metric_getTime(swigCPtr, this);
  }

  public void setTime(int _time) {
    VISHNU_IMSJNI.Metric_setTime(swigCPtr, this, _time);
  }

  public SWIGTYPE_p_ecorecpp__mapping__any eGet(int _featureID, boolean _resolve) {
    return new SWIGTYPE_p_ecorecpp__mapping__any(VISHNU_IMSJNI.Metric_eGet(swigCPtr, this, _featureID, _resolve), true);
  }

  public void eSet(int _featureID, SWIGTYPE_p_ecorecpp__mapping__any _newValue) {
    VISHNU_IMSJNI.Metric_eSet(swigCPtr, this, _featureID, SWIGTYPE_p_ecorecpp__mapping__any.getCPtr(_newValue));
  }

  public boolean eIsSet(int _featureID) {
    return VISHNU_IMSJNI.Metric_eIsSet(swigCPtr, this, _featureID);
  }

  public void eUnset(int _featureID) {
    VISHNU_IMSJNI.Metric_eUnset(swigCPtr, this, _featureID);
  }

  public SWIGTYPE_p_ecore__EClass _eClass() {
    long cPtr = VISHNU_IMSJNI.Metric__eClass(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ecore__EClass(cPtr, false);
  }

}
