/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sysfera.vishnu.api.ims.internal;

public class SysInfoOp extends EObject {
  private long swigCPtr;

  protected SysInfoOp(long cPtr, boolean cMemoryOwn) {
    super(VISHNU_IMSJNI.SWIGSysInfoOpUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SysInfoOp obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        VISHNU_IMSJNI.delete_SysInfoOp(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SysInfoOp() {
    this(VISHNU_IMSJNI.new_SysInfoOp(), true);
  }

  public void _initialize() {
    VISHNU_IMSJNI.SysInfoOp__initialize(swigCPtr, this);
  }

  public String getMachineId() {
    return VISHNU_IMSJNI.SysInfoOp_getMachineId(swigCPtr, this);
  }

  public void setMachineId(String _machineId) {
    VISHNU_IMSJNI.SysInfoOp_setMachineId(swigCPtr, this, _machineId);
  }

  public SWIGTYPE_p_ecorecpp__mapping__any eGet(int _featureID, boolean _resolve) {
    return new SWIGTYPE_p_ecorecpp__mapping__any(VISHNU_IMSJNI.SysInfoOp_eGet(swigCPtr, this, _featureID, _resolve), true);
  }

  public void eSet(int _featureID, SWIGTYPE_p_ecorecpp__mapping__any _newValue) {
    VISHNU_IMSJNI.SysInfoOp_eSet(swigCPtr, this, _featureID, SWIGTYPE_p_ecorecpp__mapping__any.getCPtr(_newValue));
  }

  public boolean eIsSet(int _featureID) {
    return VISHNU_IMSJNI.SysInfoOp_eIsSet(swigCPtr, this, _featureID);
  }

  public void eUnset(int _featureID) {
    VISHNU_IMSJNI.SysInfoOp_eUnset(swigCPtr, this, _featureID);
  }

  public SWIGTYPE_p_ecore__EClass _eClass() {
    long cPtr = VISHNU_IMSJNI.SysInfoOp__eClass(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ecore__EClass(cPtr, false);
  }

}
