#ifndef _MADAG_IDL_
#define _MADAG_IDL_


/****************************************************************************/
/* MA DAG interface                                                          */
/****************************************************************************/

interface MaDag {

  /** Used to test if this process is alive. */
  long ping();

};

#endif // _MADAG_IDL_
