/*@GODIET_LICENSE*/
/*
 * GoDIETFrame.java
 *
 * Created on 11 juin 2004, 02:34
 */

package goDiet.Interface;
import goDiet.Controller.ConsoleController;
/**
 *
 * @author  rbolze
 */
public class GoDIETFrame extends javax.swing.JFrame {
    private javax.swing.JPanel goDIETConsolePanel;
    /** Creates new form GoDIETFrame */
    public GoDIETFrame() {
        initComponents();
        goDIETConsolePanel = new GoDIETConsolePanel();
        getContentPane().add(goDIETConsolePanel, java.awt.BorderLayout.CENTER);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-400)/2, (screenSize.height-300)/2, 400, 300);
    }//GEN-END:initComponents
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
   
    public javax.swing.JPanel getGoDIETConsolePanel(){return goDIETConsolePanel;}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
