/*@GODIET_LICENSE*/
/*
 * goDIETConsolePanel.java
 *
 * Created on 11 juin 2004, 16:51
 */

package Interface;

import com.sysfera.godiet.Controller.ConsoleController;
/**
 *
 * @author  rbolze
 */
public class GoDIETConsolePanel extends javax.swing.JPanel {
    
    /** Creates new form goDIETConsolePanel */
    public GoDIETConsolePanel() {
        initComponents();
        ConsoleController consoleController = new ConsoleController(this);        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        commandTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        goDIETconsole = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        openButton = new javax.swing.JButton();
        launchButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        statusButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("GoDIET>");
        jPanel2.add(jLabel1, java.awt.BorderLayout.WEST);

        commandTextField.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel2.add(commandTextField, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.SOUTH);

        goDIETconsole.setEditable(false);
        jScrollPane1.setViewportView(goDIETconsole);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        openButton.setText("open xml");
        openButton.setMaximumSize(new java.awt.Dimension(92, 25));
        openButton.setMinimumSize(new java.awt.Dimension(92, 20));
        openButton.setPreferredSize(new java.awt.Dimension(92, 18));
        jPanel1.add(openButton);

        launchButton.setText("launch");
        launchButton.setMinimumSize(new java.awt.Dimension(75, 20));
        launchButton.setPreferredSize(new java.awt.Dimension(75, 18));
        launchButton.setEnabled(false);
        jPanel1.add(launchButton);

        stopButton.setText("stop");
        stopButton.setMinimumSize(new java.awt.Dimension(62, 18));
        stopButton.setPreferredSize(new java.awt.Dimension(62, 18));
        stopButton.setEnabled(false);
        jPanel1.add(stopButton);

        statusButton.setText("status");
        statusButton.setMinimumSize(new java.awt.Dimension(73, 18));
        statusButton.setPreferredSize(new java.awt.Dimension(73, 18));
        statusButton.setEnabled(false);
        jPanel1.add(statusButton);

        add(jPanel1, java.awt.BorderLayout.NORTH);

    }//GEN-END:initComponents
    
    public javax.swing.JTextField getCommandTextField() {return commandTextField;}
    public javax.swing.JTextArea getGoDIETConsole() {return goDIETconsole;}
    public javax.swing.JButton getOpenButton(){ return openButton;}
    public javax.swing.JButton getLaunchButton(){ return launchButton;}
    public javax.swing.JButton getStopButton(){ return stopButton;}
    public javax.swing.JButton getStatusButton(){ return statusButton;}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField commandTextField;
    private javax.swing.JTextArea goDIETconsole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton launchButton;
    private javax.swing.JButton openButton;
    private javax.swing.JButton statusButton;
    private javax.swing.JButton stopButton;
    // End of variables declaration//GEN-END:variables
    
}
